# Generated by Django 2.2.4 on 2019-08-24 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nps',
            fields=[
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('ex_value', models.IntegerField()),
                ('asset_rate', models.CharField(max_length=10)),
                ('share', models.CharField(max_length=5)),
                ('now', models.CharField(default=0, max_length=30)),
                ('past', models.CharField(default=0, max_length=30)),
                ('rate', models.CharField(default=0, max_length=30)),
                ('benefit', models.CharField(default=0, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=20)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nps.Nps')),
            ],
        ),
    ]
