# Generated by Django 2.2.3 on 2019-08-05 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartdata',
            name='code',
        ),
    ]
