# Generated by Django 2.2.4 on 2019-08-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_chartdata_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
