# Generated by Django 2.2.4 on 2019-08-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
