# Generated by Django 2.2.4 on 2019-08-12 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190811_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='usr_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='website_url',
        ),
    ]
