# Generated by Django 2.2.4 on 2019-08-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190812_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
    ]
