# Generated by Django 2.2.4 on 2019-08-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='usr_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='score',
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
