# Generated by Django 2.2.4 on 2019-08-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wallet',
            field=models.IntegerField(default=10000000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.CharField(default='10000000', max_length=30),
        ),
    ]
