# Generated by Django 2.2.4 on 2019-08-20 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190820_1009'),
        ('accounts', '0008_auto_20190819_2259'),
    ]

    operations = [
    ]
