# Generated by Django 2.2.4 on 2019-08-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190816_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='score',
        ),
        migrations.AddField(
            model_name='profile',
            name='wallet',
            field=models.IntegerField(default=10000000),
        ),
    ]
