# Generated by Django 2.2.4 on 2019-08-17 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190817_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='wallet',
            new_name='score',
        ),
    ]
