# Generated by Django 2.2.4 on 2019-08-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190817_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.CharField(default='10000000', max_length=30),
        ),
    ]
